ESPIDF ?= $(HOME)/cpp/esp-idf
CROSS_COMPILE ?= $(HOME)/cpp/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-
PYTHON=python3

BOARD ?= LILYGO_T_WATCH_2020_V1
PORT ?= /dev/ttyUSB0
FLASH_MODE ?= dio
FLASH_SIZE ?= 16MB
USER_C_MODULES=boards/LILYGO_T_WATCH_2020_V1/c_drivers

include Makefile
